---
- file:
    path: ~/.bin
    state: directory
    mode: 0700
- copy:
    src: '{{item}}'
    dest: '~/.bin/{{item}}'
    mode: 0700
  loop:
  - _docker
  - _docker-compose
  - _jq
  - alacritty-fullscreen
  - brightness.sh
  - extract
  - files
  - get_battery
  - get_cpu
  - get_date
  - get_disk
  - get_essid
  - get_iface
  - get_memory
  - get_public_ip
  - get_volume
  - headers
  - launch-chrome
  - lsproc
  - mailsync
  - metar
  - mutt-notmuch-py
  - mvi
  - psqlenv
  - pwrman
  - randombg
  - randword
  - setbg.sh
  - taf
