---
- name: Install homebrew packages
  homebrew:
    state: present
    name:
      - adns
      - afflib
      - airspy
      - ansible
      - augeas
      - bazaar
      - boost
      - cairo
      - cmake
      - ctags
      - ctop
      - dep
      - elinks
      - ext4fuse
      - fetchmail
      - ffmpeg
      - fftw
      - fontconfig
      - fontforge
      - freetype
      - fribidi
      - fzf
      - gcc
      - gd
      - gdb
      - gdbm
      - gettext
      - gflags
      - ghi
      - ghostscript
      - git
      - glib
      - glog
      - gmime
      - gmp
      - gnu-getopt
      - gnu-typist
      - gnupg
      - gnuradio
      - gnutls
      - go
      - google-java-format
      - gpgme
      - gr-osmosdr
      - graphite2
      - graphviz
      - gsl
      - hackrf
      - handbrake
      - harfbuzz
      - htop
      - hub
      - icu4c
      - irssi
      - isl
      - jemalloc
      - jpeg
      - jq
      - json-c
      - khal
      - khard
      - kubernetes-cli
      - lame
      - libarchive
      - libassuan
      - libdvdcss
      - libevent
      - libewf
      - libffi
      - libgcrypt
      - libgpg-error
      - libidn
      - libksba
      - libmagic
      - libmodplug
      - libmpc
      - libogg
      - libpng
      - libpq
      - librdkafka
      - librtlsdr
      - libssh2
      - libstfl
      - libtasn1
      - libtermkey
      - libtiff
      - libtool
      - libunistring
      - libusb
      - libuv
      - libvorbis
      - libvterm
      - libxmlsec1
      - libyaml
      - libzip
      - little-cms2
      - lldpd
      - lmdb
      - luajit
      - lynx
      - lz4
      - lzlib
      - maven
      - mitmproxy
      - mongodb
      - mosh
      - mpfr
      - msgpack
      - msmtp
      - mutt
      - mysql-client
      - ncurses
      - neovim
      - nettle
      - newsboat
      - nmap
      - node
      - notmuch
      - npth
      - numpy
      - nvm
      - oath-toolkit
      - offlineimap
      - oniguruma
      - openssl
      - osquery
      - p11-kit
      - pandoc
      - pango
      - pass
      - pcre
      - pcre2
      - pdftohtml
      - perl
      - pgformatter
      - pinentry
      - pinentry-mac
      - pixman
      - pkg-config
      - portaudio
      - postgresql@9.5
      - procmail
      - protobuf
      - pwgen
      - python
      - python@2
      - qemu
      - qrencode
      - rapidjson
      - readline
      - ripgrep
      - rocksdb
      - rtv
      - ruby
      - rust
      - s3cmd
      - sdl2
      - sdl2_gfx
      - sdl2_image
      - sdl2_mixer
      - sdl2_ttf
      - shellcheck
      - sleuthkit
      - snappy
      - sqlite
      - ssdeep
      - stow
      - talloc
      - telnet
      - testssl
      - thrift
      - tldr
      - tmux
      - tokyo-cabinet
      - travis
      - tree
      - uhd
      - um
      - unibilium
      - vdirsyncer
      - vim
      - watch
      - webp
      - wrk
      - x264
      - xapian
      - xvid
      - xz
      - yara
      - yarn
      - zeromq
      - zlib
      - zstd
- name: Install Homebrew Casks
  homebrew_cask:
    state: present
    name:
      - chromium
      - docker
      - dropbox
      - etcher
      - firefox
      - font-source-code-pro
      - fontforge
      - gimp
      - gnucash
      - gqrx
      - handbrake
      - imageoptim
      - iterm2
      - licecap
      - mactex
      - macvim
      - minecraft
      - ngrok
      - postico
      - slack
      - spotify
      - the-unarchiver
      - transmission
      - virtualbox
      - viscosity
      - vlc
      - wireshark
      - xquartz
