---
- name: Install iTerm2
  homebrew_cask:
    name: iterm2
    state: present
- name: Install tmux
  package:
    name: tmux
    state: present
- name: Install FZF
  homebrew:
    name: fzf
    state: present
- name: Install Source Code Pro font
  homebrew_cask:
    name: font-source-code-pro
    state: present
